In [1]:
import pandas as pd
import numpy as np

Q1. Pandas version

In [2]:
pd.__version__

'2.3.3'

In [31]:
url = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'
data = pd.read_csv(url)
data.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q2. Records count

In [5]:
len(data)

10000

Q3. Fuel types

In [6]:
data.fuel_type.nunique()

3

Q4. Missing values

In [12]:
(data.isna().sum() > 0).sum()

np.int64(2)

Q5. Max fuel efficiency

In [37]:
group = data[data.origin == 'Asia']
max(group.fuel_efficiency_mpg)

41.2

Q6. Median value of horsepower

In [18]:
data.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='object')

1. Find the median value of the horsepower column in the dataset.

In [32]:
before_imputation = data.horsepower.median()
before_imputation

np.float64(254.0)

2. Calculate the most frequent value of the same horsepower column.

In [33]:
most_freq = data.horsepower.value_counts().index[0]
most_freq

np.float64(252.0)

3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [34]:
data['horsepower'] = data['horsepower'].fillna(most_freq)

4. Now, calculate the median value of horsepower once again.

In [35]:
after_imputation = data.horsepower.median()
after_imputation

np.float64(252.0)

In [36]:
if after_imputation > before_imputation:
    print("Yes, it increased")
elif after_imputation < before_imputation:
    print("Yes, it decreased")
else:
    print("No change")

Yes, it decreased

Q7. Sum of weights

1. Select all the cars from Asia

In [39]:
group.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

2. Select only columns vehicle_weight and model_year

In [41]:
asia_group = group[['vehicle_weight','model_year']].head(7)
asia_group

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

4. Get the underlying NumPy array. Let's call it X.

In [42]:
X = asia_group.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [45]:
XTX = np.dot(X.T,X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

6. Invert XTX.

In [46]:
inverse_matrix = np.linalg.inv(XTX)
inverse_matrix

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [47]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

In [49]:
s = inverse_matrix @ X.T
w = s * y
w

array([[-0.27509119, -0.02155228, -0.22895733,  0.35996837, -1.18162927,
         1.21328359,  0.27042587],
       [ 0.67427208,  0.13904122,  0.5529994 , -0.71637186,  2.63152339,
        -2.54924935, -0.49946567]])

9. What's the sum of all the elements of the result?

In [51]:
round(w.sum(),3)

np.float64(0.369)